# Generated by Django 5.2.5 on 2025-09-02 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_address_zip_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='firs_name',
            new_name='first_name',
        ),
    ]
