services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
       POSTGRES_DB: ecommerce
       POSTGRES_USER: admin
       POSTGRES_PASSWORD: postgres@123
    ports:
      - "5433:5432"

volumes:
  postgres_data:

